### ISSUE TITLE
SpeechRecognitionService stops receiving response after few minutes of translation.

### ISSUE THREAD

**Issue by tbass134** [GoogleCloudPlatform/ios-docs-samples#12]
In the sample demo app, after a few minutes or so, the `SpeechRecognitionCompletionHandler` no longer receives any response. The audio data is still being sent. I have remove `[self stopAudio:nil]` when `isFinal` is TRUE in order to continue translation. Is there a time limit set on the API?

**Comment by phillco** [comment]
I've noticed the same.

**Comment by mygzi** [comment]
Read the limits more carefully:

> The maximum duration of audio sent during StreamingRecognize and SyncRecognize requests is approximately one minute.

It seems that the API fails silently as you describe - transcription simply stops but no error is issued. 

It's possible to work around this limitation (as long the speaker pauses to breathe every few minutes) by stopping and restarting the recognition process after each `isFinal` occurrence.

**Comment by tbass134** [comment]
thanks @mygzi  for the update. I was thinking about doing that, but didn't know if that was the proper way to do it

**Comment by clemens-tolboom** [comment]
Thanks for the pointer to the limits. I was planning to 'subtitle' a live audio stream for _hours_ ... guess overlapping (concurrent) streams by say 10 seconds then drop first/last word(s) from either results could work.

**Comment by clemens-tolboom** [comment]
I just tested with _Speech-gRPC-Streaming_ to see the limit is indeed just 1 minute.

I also notes that pausing (breathing) too long stopped streaming.

**Comment by mygzi** [comment]
@tbass134 @clemens-tolboom : given that it was fairly involved to get this working, I've posted my results (based on the Objective-C sample) in this [fork](https://github.com/GeneralEnchantment/ios-docs-samples). See the updated [README](https://github.com/GeneralEnchantment/ios-docs-samples/blob/master/speech/Objective-C/Speech-gRPC-Streaming/README.md) for more details.

**Comment by clemens-tolboom** [comment]
@mygzi your code looks sensible enough to make it a PR.

I've tested your changes and it seems to work OK to me. Nice work!

**Comment by iOS0340** [comment]
@mygzi I have download your code and it's working fine. When user take pause and start speech then they get the transcription. But it works for only **60 seconds** . but i want it to work for all the time when we get user audio not want to limit to **60 seconds**? is there any way to do this?

**Comment by mygzi** [comment]
@iOS0340 could add a watchdog timer to start a fresh transaction after 60 seconds of silence; I assume you would still be charged for the API usage despite the lack of transcription (can anyone confirm this?), so a side effect is that if you left it running (e.g. in the simulator) and walked away you'd run up your gcp bill.

**Comment by mygzi** [comment]
@iOS0340 added a timer that detects the end of the streaming window. Set `restartWhenSpeechless = YES` to keep things going when no speech is detected. 

@clemens-tolboom PR submitted.

**Comment by iOS0340** [comment]
@mygzi Thanks for your quick response. Let me check if it is working for me or not.

**Comment by iOS0340** [comment]
@mygzi I found one new error. some time not get 'is_final' tag but restart recognise speech. so how can we take transcribe text in this case?

**Comment by iOS0340** [comment]
In this sample when we put device on some distance from user then not working proper. some time get text from the speech and some time not goes to `END_OF_SPEECH` or `END_OF_AUDIO`. I try to restart recognition but still not working in this case. so is there any solution for this issue?

**Comment by clemens-tolboom** [comment]
I asked Google through my 'Free Trial Support' about this limit of 1 minute. @others please spam them too ;-)

I've tested PR #23 and wonder whether depending on its application words are lost / duplicated / 'out of context' which I have to experiment myself.

@mygzi are you up for a Swift variant? I need to learn either so prefer Swift as the new kid on the block :p

**Comment by mygzi** [comment]
@clemens-tolboom the current approach relies on far-side VAD (Voice Activity Detection) - that is we have to wait for the gRPC API to tell us when the user has stopped speaking, and as such is best effort. Some words will be lost if we happen to be restarting a new recognition transaction when the user starts speaking again. 

Restarting the transaction takes longer on slow connections (e.g. mobile data), so the likelihood of dropped words increases. We need to take on client side VAD to meaningfully improve this. 

Re: Swift, i haven't looked at the existing Swift samples but if they are Swift 3 I'm game.

**Comment by clemens-tolboom** [comment]
I've experimented with https://github.com/mdn/web-speech-api which has similar events. Its Google Chrome versions stops after 5 minutes which is too short for my application. Doing client side VAD was my java variant idea too.

@mygzi looking forward to the Swift variant ;-) hope I can help but now investigating AppEngine for authorization

**Comment by Ravipatel401** [comment]
**Currently I am Setuping Text To Voice google API work all over ok but when i put on server i get ERROR like this:** 

Failed to res
olve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host texttospeech.googleapis.com, cause=java.lang.RuntimeException: java.net.
UnknownHostException: texttospeech.googleapis.com
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:399)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: texttospeech.googleapis.com
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:624)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:367)
        ... 5 more

**Config :**
Linux server 
Java 8 64bit
weblogic

Please Share you idea about this
