### ISSUE TITLE
Can't do "pod install"

### ISSUE THREAD

**Issue by namanhams** [GoogleCloudPlatform/ios-docs-samples#19]
I got this error : 
[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)` depended upon by `googleapis`

My pod version is 1.0.1

**Comment by clemens-tolboom** [comment]
Your not telling where you ran the command.

I ran succesful in `ios-docs-samples/speech/Swift/Speech-gRPC-Streaming`

**Comment by Tejas-narola** [comment]
@namanhams : have you resolved this issue ?

**Comment by ecamaj** [comment]
[~/Downloads/Google Speech API/ios-docs-samples/speech/Objective-C/Speech-gRPC-Nonstreaming] pod install
Analyzing dependencies
Fetching podspec for `googleapis` from `.`
[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)` depended upon by `googleapis`

**Comment by clemens-tolboom** [comment]
Weird. This is my result on OSX El capitan

ios-docs-samples/speech/Objective-C/Speech-gRPC-Nonstreaming % pod install
Analyzing dependencies
Fetching podspec for `googleapis` from `.`
Downloading dependencies
Installing !ProtoCompiler (3.0.0)
Installing !ProtoCompiler-gRPCPlugin (1.0.0)
Installing BoringSSL (6.0)
Installing Protobuf (3.0.0)
Installing gRPC (1.0.0)
Installing gRPC-Core (1.0.0)
Installing gRPC-ProtoRPC (1.0.0)
Installing gRPC-RxLibrary (1.0.0)
Installing googleapis (0.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Speech.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 9 total pods installed.

**Comment by Tejas-narola** [comment]
@clemens-tolboom can u please pass here Podfile  ?

**Comment by clemens-tolboom** [comment]
I'm on latest master
```
commit 6432c7fc0a6dd51ed864379011006f745745e162
Merge: 1357266 f01f27a
Author: Tim Burks <timburks@google.com>
Date:   Tue Sep 20 09:35:32 2016 -0700

    Merge pull request #15 from clemens-tolboom/feature/make-sure-ios-api-key
    
    Tell developer to use 'iOS' API key.
```

which currently has https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Objective-C/Speech-gRPC-Nonstreaming/Podfile

```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
#use_frameworks!

target 'Speech' do

  pod 'googleapis', :path => '.'

end
``` 

This is my __--verbose__ result

```
pod install --verbose        
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Speech`: (``)

Fetching external sources
-> Fetching podspec for `googleapis` from `.`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A !ProtoCompiler
  A !ProtoCompiler-gRPCPlugin
  A BoringSSL
  A Protobuf
  A gRPC
  A gRPC-Core
  A gRPC-ProtoRPC
  A gRPC-RxLibrary
  A googleapis

....
```

**Comment by ecamaj** [comment]
```
ecamaj@Eduards-MacBook-Pro [~/Downloads/Google Speech API/ios-docs-samples/speech/Objective-C/Speech-gRPC-Nonstreaming] pod --version
1.1.0.rc.2
```

Before update, cocoapods version was: 1.0.0.beta.6, didn't work also.

```
ecamaj@Eduards-MacBook-Pro [~/Downloads/Google Speech API/ios-docs-samples/speech/Objective-C/Speech-gRPC-Nonstreaming] pod install
Analyzing dependencies
Fetching podspec for `googleapis` from `.`
[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)` depended upon by `googleapis`
ecamaj@Eduards-MacBook-Pro [~/Downloads/Google Speech API/ios-docs-samples/speech/Objective-C/Speech-gRPC-Nonstreaming] pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Speech`: (``)

Fetching external sources
-> Fetching podspec for `googleapis` from `.`

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)` depended upon by `googleapis`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:693:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:691:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by clemens-tolboom** [comment]
### OS
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
### POD
1.0.1

### Extra

```
pod outdated
Updating spec repo `master`

CocoaPods 1.1.0.rc.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

Analyzing dependencies
The following pod updates are available:
- Protobuf 3.0.0 -> 3.1.0 (latest version 3.1.0)
```

Hope that helps :-/

**Comment by ecamaj** [comment]
Now it suddenly worked for me. I don't know what was the problem. Yesterday I did pod repo update, but didn't work immediately after it. Now it is working.

```
Analyzing dependencies
Fetching podspec for `googleapis` from `.`
Downloading dependencies
Installing !ProtoCompiler (3.0.0)
Installing !ProtoCompiler-gRPCPlugin (1.0.0)
Installing BoringSSL (6.0)
Installing Protobuf (3.1.0)
Installing gRPC (1.0.0)
Installing gRPC-Core (1.0.0)
Installing gRPC-ProtoRPC (1.0.0)
Installing gRPC-RxLibrary (1.0.0)
Installing googleapis (0.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Speech.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 9 total pods installed.

```

**Comment by clemens-tolboom** [comment]
Nice it finally works.

**Comment by damienromito** [comment]
`pod outdated` solved it for me

**Comment by AnilkumarRabhasa** [comment]
@clemens-tolboom @ecamaj This installation process working fine, But, How can we integrate to my existing project, As per this installation process, its creating new workspace like new project. We want to integrate to our existing project, can you please provide the steps for that?

**Comment by clemens-tolboom** [comment]
I have no idea as no existing project. I was only testing the stuff myself.

**Comment by adarshroy** [comment]
I have copied the 'google' folder and 'googleapis.podspec' file from Sample to my own demoProject. Then did the pod_install, which successfully run. I am able to integrate speech-to-text.

But a new issue arose, when I was trying to install a new pod. It simply fails.
Doing 'pod spec lint --verbose' yields:

```
Error installing googleapis  -> googleapis (0.0.1)
warning: Could not find remote branch 0.0.1 to clone.
fatal: Remote branch 0.0.1 not found in upstream origin
```

I know this is the issue with the podspec file, what to do I dont know

**Comment by grehce** [comment]
Copying @smindia1988 post here: https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/53

googleapis.podspec.zip

Issue:
[!] No podspec found for googleapis in .

Solution:
Step-1:
You need to put "googleapis.podspec" file in same directory where your pod file is located.

Step-2:
Open terminal and reach to the directory where your pod file located by using "cd" command

Step-3:
Then run command "pod update" in terminal

Its done. Your googleapis pod installation begins!!! Hurray!!!
