### ISSUE TITLE
Pod install fails - No such file or directory

### ISSUE THREAD

**Issue by kirualex** [GoogleCloudPlatform/ios-docs-samples#35]
Please execute this shell command then replace it with your console output.

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
Cocoapods 1.1.1
```

---

### Problem | Feature

The usual `pod install` fails for some reason.

```Errno::ENOENT - No such file or directory - /Users/alex/Documents/Developpement/iOS/MY_PROJECT/google/Protobuf/objectivec
/Users/alex/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/project.rb:186:in `realpath'
/Users/alex/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/project.rb:186:in `realpath'
/Users/alex/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/project.rb:186:in `add_file_reference'
/Users/alex/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:187:in `block (2 levels) in add_file_accessors_paths_to_pods_group'```

**Comment by kirualex** [comment]
Ok, I fixed it using the original project files. Mines must have got corrupted for some reason.
